In [1]:
import pandas as pd

from initialize_shipping_time_df import get_article_production_duration_df

In [2]:
all_production_time = get_article_production_duration_df()

all_products = all_production_time

all_products = all_products.drop(columns=["duration_producer", "duration_coating"])

all_products["amount"] = int(0)

all_products["min_amount"] = int(5)

all_products

,SKU,Beschichtung,producer,duration,production_line,amount,min_amount
0,9101UB,unbeschichtet,3,10,1,0,5
1,9101FZ,feuerverzinkt,3,25,1,0,5
2,9101DX,DB 703,3,25,1,0,5
3,9101SF,Sonderfarben,3,25,1,0,5
4,9102UB,unbeschichtet,2,20,1,0,5
...,...,...,...,...,...,...,...
66,SZ21022,unbeschichtet,1,15,3,0,5
67,SZ2102SF,Sonderfarbe,1,30,3,0,5
68,SZ21031,pulverbeschichtet DB703,1,30,3,0,5
69,SZ21032,unbeschichtet,1,15,3,0,5
70,SZ2103SF,Sonderfarbe,1,30,3,0,5

In [4]:
article_id = "9101DX"
article_df = all_products[all_products["SKU"].apply(str) == article_id]
if article_df is None:
    msg: str = f"tried to retrieve information about article: {article_id}, but article is None"
    print(msg)
    raise ValueError(msg)

type(article_df)

from domain.model.article import Article
article = Article(
    sku=str(article_df["SKU"].item()),
    coating=str(article_df["Beschichtung"].item()),
    producer_id=int(article_df["producer"].item()),
    delivery_time=int(article_df["duration"].item()),
    production_line=int(article_df["production_line"].item())
)

article

Article(sku='9101DX', coating='DB 703', producer_id=3, delivery_time=25, production_line=1)

In [9]:
from datetime import datetime, timedelta, date
import random

today = datetime.today().date()

data = {
    "date": [today + timedelta(days=i) for i in range(10)],
    "quantity": [random.randint(1, 100) for _ in range(10)],
}

df = pd.DataFrame(data)

# df["date"] = df["date"].apply(lambda d: d if isinstance(d, date) else d.date())

type(df["date"][0])

datetime.date

In [20]:
start_date = datetime.today().date()
end_date = start_date + timedelta(days=30)

# Alle Tage im Intervall sammeln
num_days: int = (end_date - start_date).days + 1
days: list[date] = [start_date + timedelta(days=i) for i in range(num_days)]

# Mögliche Labels
weather_labels: list[str] = ["sun", "normal", "rain"]

# Dummy-Daten generieren (später durch echte Forecasts ersetzbar)
data = {
    "date": days,
    "qty": [random.randint(0, 50) for _ in days],                       # int
    "tavg": [round(random.uniform(-5.0, 30.0), 1) for _ in days],         # float
    "weather_label": [random.choice(weather_labels) for _ in days],       # str
    "sale_active": [random.choice([True, False]) for _ in days],          # bool
    "sales_percent": [round(random.uniform(0.0, 0.5), 2) for _ in days],  # float (0–0.5)
}

df: pd.DataFrame = pd.DataFrame(data)

# Sicherstellen, dass "date" vom Typ datetime.date ist
df["date"] = df["date"].dt.date if hasattr(df["date"], "dt") else df["date"]

df

          date  qty  tavg weather_label  sale_active  sales_percent
0   2025-11-29   29  24.6           sun         True           0.38
1   2025-11-30   16   2.5        normal         True           0.32
2   2025-12-01   18   7.1          rain         True           0.42
3   2025-12-02   31  29.6           sun         True           0.03
4   2025-12-03    5  -2.9        normal        False           0.02
5   2025-12-04   11  11.9           sun         True           0.24
6   2025-12-05   17  -3.0          rain        False           0.35
7   2025-12-06   18  23.7           sun         True           0.32
8   2025-12-07   45  14.2        normal        False           0.43
9   2025-12-08   25  26.5        normal        False           0.27
10  2025-12-09   47  16.9           sun        False           0.50
11  2025-12-10    7  16.7           sun         True           0.33
12  2025-12-11    2  -3.5          rain        False           0.17
13  2025-12-12   30  12.4           sun         True           0.48
14  2025-12-13   11  -2.3        normal         True           0.27
15  2025-12-14   34  15.5        normal         True           0.45
16  2025-12-15   17   5.6          rain         True           0.15
17  2025-12-16   26  11.8           sun         True           0.37
18  2025-12-17   47   1.4        normal        False           0.04
19  2025-12-18   44  13.4           sun         True           0.14
20  2025-12-19   16  13.6          rain        False           0.17
21  2025-12-20   22  -1.4        normal        False           0.48
22  2025-12-21    7  15.5           sun         True           0.30
23  2025-12-22   49  10.2           sun        False           0.29
24  2025-12-23   19  28.5           sun        False           0.16
25  2025-12-24   22  -1.1           sun        False           0.34
26  2025-12-25    1   2.5        normal        False           0.12
27  2025-12-26   30  -2.2        normal        False           0.21
28  2025-12-27    7   7.1           sun        False           0.47
29  2025-12-28   31  10.0          rain        False           0.22
30  2025-12-29    0  11.4        normal         True           0.18

In [18]:

num_days: int = (end_date - start_date).days + 1

data = {
    "date": [today + timedelta(days=i) for i in range(num_days)],
    "quantity": [random.randint(0, 20) for _ in range(num_days)],
}

df = pd.DataFrame(data)
df

          date  quantity
0   2025-11-29         1
1   2025-11-30         9
2   2025-12-01        18
3   2025-12-02         8
4   2025-12-03        11
5   2025-12-04         3
6   2025-12-05         6
7   2025-12-06         6
8   2025-12-07        13
9   2025-12-08        20
10  2025-12-09         7
11  2025-12-10         7
12  2025-12-11        14
13  2025-12-12        15
14  2025-12-13        14
15  2025-12-14        10
16  2025-12-15         8
17  2025-12-16         2
18  2025-12-17         2
19  2025-12-18        19
20  2025-12-19         2
21  2025-12-20        20
22  2025-12-21        17
23  2025-12-22         0
24  2025-12-23        12
25  2025-12-24         3
26  2025-12-25         9
27  2025-12-26        17
28  2025-12-27         3
29  2025-12-28         0
30  2025-12-29        10